ALTER TABLE events ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW';
ALTER TABLE events ALTER COLUMN status SET DEFAULT 'PENDING_REVIEW';
UPDATE events SET status = 'PENDING_REVIEW' WHERE status IS NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS alcohol BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE events SET alcohol = COALESCE(alcohol, FALSE) WHERE alcohol IS NULL;
ALTER TABLE events ALTER COLUMN flyer_url DROP NOT NULL;
UPDATE events SET event_date = event_datetime::date WHERE event_date IS NULL AND event_datetime IS NOT NULL;
ALTER TABLE events ALTER COLUMN event_date SET DEFAULT CURRENT_DATE;
ALTER TABLE events ALTER COLUMN event_date SET NOT NULL;
