ALTER TABLE events
    ADD COLUMN IF NOT EXISTS admin_notes TEXT,
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS approved_by UUID,
    ADD COLUMN IF NOT EXISTS disabled_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS disabled_by UUID,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS deleted_by UUID;

ALTER TABLE events
    ALTER COLUMN status SET DEFAULT 'PENDING_REVIEW';

UPDATE events SET status = 'APPROVED' WHERE status = 'LIVE';
UPDATE events SET status = 'DISABLED' WHERE status = 'REJECTED';
UPDATE events SET status = 'PENDING_REVIEW'
WHERE status NOT IN ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'DISABLED', 'DELETED');

UPDATE events SET is_live = false WHERE status IN ('DISABLED', 'DELETED');
